# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses: [192.168.136.5/24]
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
      routes:
        - to: default
          via: 192.168.136.1

    enp0s8:
      dhcp4: false
      addresses: [192.168.1.1/24]
  version: 2
